fixit

diff --git a/.github/workflows/ci-code-approval.yml b/.github/workflows/ci-code-approval.yml
--- a/.github/workflows/ci-code-approval.yml
+++ b/.github/workflows/ci-code-approval.yml
@@ -166,3 +166,32 @@ jobs:
           file-path: ${{ github.workspace }}/routes-validator-report.md
           pr-number: ${{ github.event.pull_request.number }}
           create-if-not-exists: true
+
+  diff:
+    name: "Diff"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version-file: 'go.mod'
+          cache-dependency-path: "**/*.sum"
+
+      - name: Run Mage
+        uses: magefile/mage-action@v3
+        with:
+          version: latest
+          args: fixit
+
+      - name: Check Diff
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "[ERROR] Changes detected:"
+            git status --porcelain
+
+            echo "Make sure to run 'mage fixit' before committing."
+            exit 1
+          fi
